name: CI/CD Docker Build
on:
  push:
    branches: [master]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/currencyserv:latest .


      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/currencyserv:latest


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/currencyserv:latest

